# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build Webapp Server
      run: dotnet build ./webapp/server/AppointmentPlanner/AppointmentPlanner.csproj
    - name: Build Webapp Wasm
      run: dotnet build ./webapp/wasm/AppointmentPlanner/AppointmentPlanner/AppointmentPlanner.csproj

